name: Check Version

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "packages/extension/docs/**"
      - "packages/model/**"
      - "packages/plugin/**"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # This one-liner will exit 1 if the current version in package.json exists as a tag.
      - name: Ensure new version
        run: |
          ! git tag -l | grep "v$(node -e 'console.log(require("./package.json").version)')"
