name: Publish NPM Package for Plugin

on:
  push:
    branches:
      - master
    paths:
      - "plugin/**"

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Project
        run: yarn install --frozen-lockfile
        working-directory: plugin

      - name: Publish Package
        run: npm publish
        if: ${{ github.repository_owner == 'anz-bank' }}
        working-directory: plugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}