name: Publish NPM Package for Model

on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "docs/**"
      - "packages/model/**"

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/model

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Project
        run: yarn install --frozen-lockfile

      - name: Publish Package
        run: npm publish
        if: ${{ github.repository_owner == 'anz-bank' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
