name: Publish NPM Package for Plugin

on:
  push:
    branches:
      - master
    paths:
      - "plugin/**"

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Project
        run: npm ci
        working-directory: plugin

      - name: Publish Package
        run: npm publish
        working-directory: plugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}