name: Publish packages

on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "packages/**"

env:
  NPM_CONFIG_REGISTRY: ${{ vars.NPM_CONFIG_REGISTRY }}

jobs:
  publish-to-npm:
    if: ${{ github.repository_owner == 'anz-bank' }}
    runs-on: ${{ vars.RUNNER_UBUNTU && fromJSON(vars.RUNNER_UBUNTU) || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages deps
        run: |
          # install yarn if needed
          npm i -g yarn

          # switch registry in lock file
          if [ -n "${{ env.NPM_CONFIG_REGISTRY }}" ]; then
            sed -i'.bak' 's#https://registry.npmjs.org#${{ env.NPM_CONFIG_REGISTRY }}#' yarn.lock
            sed -i'.bak' 's#https://registry.yarnpkg.com#${{ env.NPM_CONFIG_REGISTRY }}#' yarn.lock
            rm yarn.lock.bak
          fi

          yarn install --frozen-lockfile

      - name: Build packages
        run: yarn lerna run build

      - name: Configure NPM auth
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          git update-index --assume-unchanged .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish packages
        run: yarn lerna publish from-package --contents=dist --yes
